### ISSUE TITLE
Creating a parameter throws 'botocore' is not defined

### ISSUE THREAD

**Issue by mtb-xt** [BWITS/ssm_parameter_store#7]
Hello, 

I'm trying to use the example to create a parameter:
```
         - name: Create or update key/value pair in aws parameter store
           ssm_parameter_store:
             name: "Hello"
             description: "This is your first key"
             value: "World"


```

It results in this:
```
Traceback (most recent call last):
  File "/tmp/ansible_i50RV5/ansible_module_ssm_parameter_store.py", line 221, in <module>
    main()
  File "/tmp/ansible_i50RV5/ansible_module_ssm_parameter_store.py", line 210, in main
    except botocore.exceptions.NoCredentialsError as e:
NameError: global name 'botocore' is not defined

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_i50RV5/ansible_module_ssm_parameter_store.py\", line 221, in <module>\n    main()\n  File \"/tmp/ansible_i50RV5/ansible_module_ssm_parameter_store.py\", line 210, in main\n    except botocore.exceptions.NoCredentialsError as e:\nNameError: global name 'botocore' is not defined\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```

Strange thing that lookups work!
```
         - name: Parameters can be provided after the key be more specific about what to retrieve
           debug: msg='key contains {{item}}'
           with_ssm:
             - '/UAT'
             - 'region=ap-southeast-2'
```

**Comment by ozbillwang** [comment]
Thanks for reporting this issue. 

I saw this error when try to merge the code to its upstream via PR (https://github.com/ansible/ansible/pull/23460).

```
Failures

 ansible-test / sanity / pylint

 failure: The test `ansible-test sanity --test pylint` failed with the following error:

lib/ansible/modules/cloud/amazon/ssm_parameter_store.py:209:11: undefined-variable Undefined variable 'botocore'
 ansible-test / sanity / validate-modules

 failure: The test `ansible-test sanity --test validate-modules` failed with the following errors:

lib/ansible/modules/cloud/amazon/ssm_parameter_store.py:0:0: E307 version_added should be 2.5. Currently 2.4
lib/ansible/modules/cloud/amazon/ssm_parameter_store.py:0:0: E316 ANSIBLE_METADATA.metadata_version: not a valid value for dictionary value @ data['metadata_version']. Got '1.0'
```

**Comment by mtb-xt** [comment]
I got it with ansible 2.3.0.0 <_< 
```
[hawara@shinkiro ansible]$ ansible-playbook --version
ansible-playbook 2.3.0.0
  config file = /home/hawara/work/deploy/aws/ansible/ansible.cfg
  configured module search path = ['/home/hawara/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules', './library']
  python version = 3.6.2 (default, Jul 20 2017, 03:52:27) [GCC 7.1.1 20170630]

```

**Comment by mtb-xt** [comment]
@ozbillwang I believe that I've found the source of the issue - the code itself is fine, but pylint was complaining. Please take a look at the pull request I've opened - I've pushed a fix there - https://github.com/BWITS/ssm_parameter_store/pull/8/commits/ce7b06f86d42966733e447e83c1da08122c37f6f

**Comment by ozbillwang** [comment]
I have accepted the commit `ce7b06f` , but I don't know how to adapt your codes with history (such as your name, etc). I did the change manually. 

- add the change to master branch
- update the PR  (https://github.com/ansible/ansible/pull/23460), pylint error is gone.
